[package]
name = "price-checker"
version = "0.1.0"
edition = "2018"

[features]
no-entrypoint = []

[dependencies]
solana-program = "=1.7.9"
pyth-client = "0.2.2"
thiserror = "1.0.24"

[dev-dependencies]
solana-program-test = "=1.7.9"
solana-sdk = "=1.7.9"

[lib]
crate-type = ["cdylib", "lib"]